---

### Installation

- name: Ensure /etc/containers exists
  become: true
  become_user: root
  file:
    state: directory
    path: /etc/containers

# Podman uses this, on at least Ubuntu, to do port publishing.
- name: Ensure iptables is installed
  become: true
  become_user: root
  package:
    name: iptables

- include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include_tasks: podman_service.yml
  loop: "{{ podman_services }}"
  loop_control:
    loop_var: service
