---

- name: "Download {{ service.image_name }} image"
  podman_image:
    name: "{{ service.image_name }}:{{ service.image_version | default('latest') }}"
  register: podman_image_download

- name: Generate service name
  set_fact:
    __podman_service_name: "{{ service.service_name | default(service.image_name + '-podman') }}"

- name: "Install  service"
  template:
    src: "podman.service"
    dest: '/etc/systemd/system/{{ __podman_service_name }}.service'
  register: podman_service_file

- name: "Restart {{ service.image_name }}"
  systemd:
    name: "{{ service.image_name }}-podman"
    state: restarted
    enabled: true
    daemon_reload: true
  when: podman_image_download.changed or podman_service_file.changed
